### PR TITLE
Change to new modding structure

### PR DESCRIPTION
**Pull request by DasCapschen**

### CODE REVIEW

**Comment by HaSa1002** [comment]
Breaks at save_world, because of non existing world.
Editor.gd:328

Probably because the content.tres refers to res:// paths. Perhaps we could add something to enable loading worlds from an editor run instance as well? Because otherwise we are not going to debug anything 😅

**Comment by HaSa1002** [comment]
See https://github.com/Libre-TrainSim/Libre-TrainSim/issues/224

**Comment by DasCapschen** [comment]
I thought it is not possible to load mods from an editor build, because it messes with Godot?

Also, the editor save function writes to the users picked directory...
```gdscript
 func save_world_step_2(send_message: bool = true) -> void:
     var packed_scene = PackedScene.new()
     var result = packed_scene.pack($World)
     if result == OK:
         var error = ResourceSaver.save(editor_directory + "Worlds/" + Root.current_editor_track + "/" + Root.current_editor_track + ".tscn", packed_scene)
         if error != OK:
             send_message("An error occurred while saving the scene to disk.")
             return
```

**Comment by HaSa1002** [comment]
Mod Loading is fine. PCK Loading is the issue. As long as we load the files correctlz there is no issue. We just can't load a PCK

**Review by HaSa1002 — APPROVED** [review]
tested. Works fine after a long way :)

**Pull request merged**
